import type { Candidate } from "../types/candidate";

export const mockCandidates: Candidate[] = [
  {
    id: "1",
    name: "Jana Patton",
    company: "Intern at Northwest Airlines Corp",
    jobTitle: "Digital Marketing Specialist",
    jobCode: "(O26)",
    statusNotes: "↑ Collect feedback in Application Review",
    statusActionText: "Collect Feedback",
    statusActionLink: "#",
    designation: "Application Review",
  },
  {
    id: "2",
    name: "Zona Cohen",
    company: "Georgia Gulf Corporation",
    jobTitle: "Digital Marketing Specialist",
    jobCode: "(O26)",
    statusNotes: "↑ Collect feedback in Reference Check",
    statusActionText: "Collect Feedback",
    statusActionLink: "#",
    designation: "Former Manager",
  },
  {
    id: "3",
    name: "Allan Peterson",
    company: "Executive VP at Continental Airlines Inc.",
    jobTitle: "Digital Marketing Specialist",
    jobCode: "(O26)",
    statusNotes: "↑ Collect feedback in Application Review",
    statusActionText: "",
    statusActionLink: "#",
    designation: "",
  },
  {
    id: "4",
    name: "Randy Beebe",
    company: "Riverwood Holding Inc.",
    jobTitle: "Digital Marketing Specialist",
    jobCode: "(O26)",
    statusNotes: "↑ Interviews to schedule for Face to Face",
    statusActionText: "",
    statusActionLink: "#",
    designation: "",
    additionalInfo: {
      availabilityText: "Not Requested",
      requestLink: "#",
    },
    interviews: [
      { type: "Cultural Add Interview", manualLink: "#", autoLink: "#" },
      { type: "Peer Panel Interview", manualLink: "#", autoLink: "#" },
      { type: "Case Study", manualLink: "#", autoLink: "#" },
      { type: "Executive Interview", manualLink: "#", autoLink: "#" },
    ],
  },
  {
    id: "5",
    name: "Luann Stevens",
    company: "Development Manager at Public Service Enterprise Group Inc.",
    jobTitle: "Digital Marketing Specialist",
    jobCode: "(O26)",
    statusNotes: "↑ Interview to schedule for Phone Interview",
    statusActionText: "",
    statusActionLink: "#",
    designation: "",
  },
];
