import type { Candidate } from "../types/candidate";

export const mockCandidates: Candidate[] = [
  {
    id: "1",
    name: "Jana Patton",
    company: "Northwest Airlines Corp",
    jobTitle: "Digital Marketing Specialist",
    jobCode: "(O26)",
    statusNotes: "↑ Collect feedback in Application Review",
    statusActionText: "Collect Feedback",
    statusActionLink: "#",
    designation: "Application Review",
    applicationType: "full-time",
    jobCategory: "marketing",
    crm: "hubspot",
    profileStatus: "verified",
    source: "referral",
    responsibility: "manager",
    pipelineTask: "pending",
    education: "bachelor",
  },
  {
    id: "2",
    name: "Zona Cohen",
    company: "Georgia Gulf Corporation",
    jobTitle: "Digital Marketing Specialist",
    jobCode: "(O26)",
    statusNotes: "↑ Collect feedback in Reference Check",
    statusActionText: "Collect Feedback",
    statusActionLink: "#",
    designation: "Former Manager",
    applicationType: "contract",
    jobCategory: "marketing",
    crm: "salesforce",
    profileStatus: "verified",
    source: "job-board",
    responsibility: "team-lead",
    pipelineTask: "in-progress",
    education: "master",
  },
  {
    id: "3",
    name: "Allan Peterson",
    company: "Continental Airlines Inc.",
    jobTitle: "Digital Marketing Specialist",
    jobCode: "(O26)",
    statusNotes: "↑ Collect feedback in Application Review",
    statusActionText: "",
    statusActionLink: "#",
    designation: "",
    applicationType: "full-time",
    jobCategory: "marketing",
    crm: "zoho",
    profileStatus: "unverified",
    source: "social-media",
    responsibility: "contributor",
    pipelineTask: "completed",
    education: "phd",
  },
  {
    id: "4",
    name: "Randy Beebe",
    company: "Riverwood Holding Inc.",
    jobTitle: "Digital Marketing Specialist",
    jobCode: "(O26)",
    statusNotes: "↑ Interviews to schedule for Face to Face",
    statusActionText: "",
    statusActionLink: "#",
    designation: "",
    additionalInfo: {
      availabilityText: "Not Requested",
      requestLink: "#",
    },
    interviews: [
      { type: "Cultural Add Interview", manualLink: "#", autoLink: "#" },
      { type: "Peer Panel Interview", manualLink: "#", autoLink: "#" },
    ],
    applicationType: "part-time",
    jobCategory: "marketing",
    crm: "hubspot",
    profileStatus: "verified",
    source: "referral",
    responsibility: "manager",
    pipelineTask: "pending",
    education: "bachelor",
  },
  {
    id: "5",
    name: "Luann Stevens",
    company: "Public Service Enterprise Group Inc.",
    jobTitle: "Digital Marketing Specialist",
    jobCode: "(O26)",
    statusNotes: "↑ Interview to schedule for Phone Interview",
    statusActionText: "",
    statusActionLink: "#",
    designation: "",
    applicationType: "full-time",
    jobCategory: "marketing",
    crm: "salesforce",
    profileStatus: "verified",
    source: "job-board",
    responsibility: "team-lead",
    pipelineTask: "in-progress",
    education: "master",
  },
  // --- 20 more candidates ---
  {
    id: "6",
    name: "Tina Marshall",
    company: "Tech Solutions Inc.",
    jobTitle: "Software Engineer",
    jobCode: "(E12)",
    statusNotes: "Awaiting Manager Review",
    statusActionText: "Schedule Interview",
    statusActionLink: "#",
    designation: "Engineer",
    applicationType: "full-time",
    jobCategory: "engineering",
    crm: "zoho",
    profileStatus: "verified",
    source: "job-board",
    responsibility: "contributor",
    pipelineTask: "in-progress",
    education: "bachelor",
  },
  {
    id: "7",
    name: "Kyle Armstrong",
    company: "Creative Designs LLC",
    jobTitle: "UI/UX Designer",
    jobCode: "(D08)",
    statusNotes: "Portfolio Pending",
    statusActionText: "",
    statusActionLink: "#",
    designation: "Designer",
    applicationType: "part-time",
    jobCategory: "design",
    crm: "hubspot",
    profileStatus: "unverified",
    source: "social-media",
    responsibility: "contributor",
    pipelineTask: "pending",
    education: "master",
  },
  {
    id: "8",
    name: "Melissa Ford",
    company: "Global Marketing Co.",
    jobTitle: "Marketing Manager",
    jobCode: "(M04)",
    statusNotes: "Approved by HR",
    statusActionText: "Send Offer",
    statusActionLink: "#",
    designation: "Manager",
    applicationType: "full-time",
    jobCategory: "marketing",
    crm: "salesforce",
    profileStatus: "verified",
    source: "referral",
    responsibility: "manager",
    pipelineTask: "completed",
    education: "master",
  },
  {
    id: "9",
    name: "David Lin",
    company: "TechWave Ltd.",
    jobTitle: "Backend Engineer",
    jobCode: "(E21)",
    statusNotes: "Pending Interview",
    statusActionText: "Schedule Interview",
    statusActionLink: "#",
    designation: "Engineer",
    applicationType: "contract",
    jobCategory: "engineering",
    crm: "zoho",
    profileStatus: "unverified",
    source: "job-board",
    responsibility: "contributor",
    pipelineTask: "pending",
    education: "bachelor",
  },
  {
    id: "10",
    name: "Laura Kim",
    company: "DesignHub Inc.",
    jobTitle: "Graphic Designer",
    jobCode: "(D05)",
    statusNotes: "Portfolio approved",
    statusActionText: "Schedule Interview",
    statusActionLink: "#",
    designation: "Designer",
    applicationType: "full-time",
    jobCategory: "design",
    crm: "hubspot",
    profileStatus: "verified",
    source: "social-media",
    responsibility: "team-lead",
    pipelineTask: "in-progress",
    education: "bachelor",
  },
  {
    id: "11",
    name: "Michael Scott",
    company: "Dunder Mifflin",
    jobTitle: "Sales Manager",
    jobCode: "(S02)",
    statusNotes: "Pending Reference Check",
    statusActionText: "Collect Feedback",
    statusActionLink: "#",
    designation: "Manager",
    applicationType: "full-time",
    jobCategory: "marketing",
    crm: "salesforce",
    profileStatus: "verified",
    source: "referral",
    responsibility: "manager",
    pipelineTask: "pending",
    education: "master",
  },
  {
    id: "12",
    name: "Pam Beesly",
    company: "Dunder Mifflin",
    jobTitle: "Graphic Designer",
    jobCode: "(D01)",
    statusNotes: "Portfolio Pending",
    statusActionText: "",
    statusActionLink: "#",
    designation: "Designer",
    applicationType: "part-time",
    jobCategory: "design",
    crm: "zoho",
    profileStatus: "unverified",
    source: "social-media",
    responsibility: "contributor",
    pipelineTask: "pending",
    education: "bachelor",
  },
  {
    id: "13",
    name: "Jim Halpert",
    company: "Dunder Mifflin",
    jobTitle: "Marketing Specialist",
    jobCode: "(M01)",
    statusNotes: "Approved",
    statusActionText: "Send Offer",
    statusActionLink: "#",
    designation: "Team Lead",
    applicationType: "full-time",
    jobCategory: "marketing",
    crm: "hubspot",
    profileStatus: "verified",
    source: "job-board",
    responsibility: "team-lead",
    pipelineTask: "completed",
    education: "master",
  },
  {
    id: "14",
    name: "Dwight Schrute",
    company: "Dunder Mifflin",
    jobTitle: "Sales Executive",
    jobCode: "(S03)",
    statusNotes: "Pending HR Approval",
    statusActionText: "Collect Feedback",
    statusActionLink: "#",
    designation: "Manager",
    applicationType: "contract",
    jobCategory: "marketing",
    crm: "zoho",
    profileStatus: "unverified",
    source: "referral",
    responsibility: "manager",
    pipelineTask: "in-progress",
    education: "bachelor",
  },
  {
    id: "15",
    name: "Stanley Hudson",
    company: "Dunder Mifflin",
    jobTitle: "Operations Specialist",
    jobCode: "(O01)",
    statusNotes: "Pending Review",
    statusActionText: "",
    statusActionLink: "#",
    designation: "Contributor",
    applicationType: "full-time",
    jobCategory: "engineering",
    crm: "hubspot",
    profileStatus: "verified",
    source: "job-board",
    responsibility: "contributor",
    pipelineTask: "pending",
    education: "master",
  },
  {
    id: "16",
    name: "Phyllis Vance",
    company: "Dunder Mifflin",
    jobTitle: "Marketing Coordinator",
    jobCode: "(M05)",
    statusNotes: "Pending Interview",
    statusActionText: "Schedule Interview",
    statusActionLink: "#",
    designation: "Team Lead",
    applicationType: "part-time",
    jobCategory: "marketing",
    crm: "salesforce",
    profileStatus: "verified",
    source: "referral",
    responsibility: "team-lead",
    pipelineTask: "in-progress",
    education: "bachelor",
  },
  {
    id: "17",
    name: "Kevin Malone",
    company: "Dunder Mifflin",
    jobTitle: "Accountant",
    jobCode: "(F01)",
    statusNotes: "Pending Review",
    statusActionText: "",
    statusActionLink: "#",
    designation: "Contributor",
    applicationType: "full-time",
    jobCategory: "engineering",
    crm: "zoho",
    profileStatus: "unverified",
    source: "social-media",
    responsibility: "contributor",
    pipelineTask: "completed",
    education: "master",
  },
  {
    id: "18",
    name: "Angela Martin",
    company: "Dunder Mifflin",
    jobTitle: "HR Specialist",
    jobCode: "(H01)",
    statusNotes: "Pending Reference Check",
    statusActionText: "Collect Feedback",
    statusActionLink: "#",
    designation: "Manager",
    applicationType: "contract",
    jobCategory: "marketing",
    crm: "hubspot",
    profileStatus: "verified",
    source: "job-board",
    responsibility: "manager",
    pipelineTask: "pending",
    education: "bachelor",
  },
  {
    id: "19",
    name: "Oscar Martinez",
    company: "Dunder Mifflin",
    jobTitle: "Financial Analyst",
    jobCode: "(F02)",
    statusNotes: "Pending Review",
    statusActionText: "",
    statusActionLink: "#",
    designation: "Contributor",
    applicationType: "full-time",
    jobCategory: "engineering",
    crm: "salesforce",
    profileStatus: "verified",
    source: "referral",
    responsibility: "contributor",
    pipelineTask: "in-progress",
    education: "master",
  },
  {
    id: "20",
    name: "Meredith Palmer",
    company: "Dunder Mifflin",
    jobTitle: "Operations Coordinator",
    jobCode: "(O02)",
    statusNotes: "Pending Interview",
    statusActionText: "Schedule Interview",
    statusActionLink: "#",
    designation: "Contributor",
    applicationType: "part-time",
    jobCategory: "engineering",
    crm: "zoho",
    profileStatus: "unverified",
    source: "social-media",
    responsibility: "contributor",
    pipelineTask: "pending",
    education: "bachelor",
  },
  {
    id: "21",
    name: "Creed Bratton",
    company: "Dunder Mifflin",
    jobTitle: "QA Specialist",
    jobCode: "(Q01)",
    statusNotes: "Pending Review",
    statusActionText: "",
    statusActionLink: "#",
    designation: "Contributor",
    applicationType: "full-time",
    jobCategory: "engineering",
    crm: "hubspot",
    profileStatus: "verified",
    source: "job-board",
    responsibility: "contributor",
    pipelineTask: "completed",
    education: "master",
  },
  {
    id: "22",
    name: "Kelly Kapoor",
    company: "Dunder Mifflin",
    jobTitle: "Marketing Specialist",
    jobCode: "(M06)",
    statusNotes: "Pending Approval",
    statusActionText: "Send Offer",
    statusActionLink: "#",
    designation: "Team Lead",
    applicationType: "contract",
    jobCategory: "marketing",
    crm: "salesforce",
    profileStatus: "verified",
    source: "referral",
    responsibility: "team-lead",
    pipelineTask: "in-progress",
    education: "bachelor",
  },
  {
    id: "23",
    name: "Ryan Howard",
    company: "Dunder Mifflin",
    jobTitle: "Temp Worker",
    jobCode: "(T01)",
    statusNotes: "Pending Interview",
    statusActionText: "",
    statusActionLink: "#",
    designation: "Contributor",
    applicationType: "part-time",
    jobCategory: "engineering",
    crm: "zoho",
    profileStatus: "unverified",
    source: "social-media",
    responsibility: "contributor",
    pipelineTask: "pending",
    education: "high-school",
  },
  {
    id: "24",
    name: "Jan Levinson",
    company: "Dunder Mifflin",
    jobTitle: "Executive Manager",
    jobCode: "(E01)",
    statusNotes: "Pending Approval",
    statusActionText: "Send Offer",
    statusActionLink: "#",
    designation: "Manager",
    applicationType: "full-time",
    jobCategory: "marketing",
    crm: "hubspot",
    profileStatus: "verified",
    source: "referral",
    responsibility: "manager",
    pipelineTask: "completed",
    education: "master",
  },
  {
    id: "25",
    name: "Holly Flax",
    company: "Dunder Mifflin",
    jobTitle: "HR Manager",
    jobCode: "(H02)",
    statusNotes: "Pending Review",
    statusActionText: "Schedule Interview",
    statusActionLink: "#",
    designation: "Manager",
    applicationType: "contract",
    jobCategory: "marketing",
    crm: "salesforce",
    profileStatus: "verified",
    source: "job-board",
    responsibility: "manager",
    pipelineTask: "in-progress",
    education: "master",
  },
];
